import Head from 'next/head'

export default function Forecast() {

  return (
    <>
      <Head>
        <title>Forecast | Zeleri</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ height: '92.8vh', marginLeft: '25rem' }}>
        Forecast
      </div>
    </>
  )
}