import SunnyIcon from '@/public/icons/Sunny'
import { useGetWeatherByNameQuery } from '@/services/getHome'
import { RootState } from '@/store/store'
import Head from 'next/head'
import { useSelector } from 'react-redux'

export default function Home() {
  const { entities } = useSelector((state: RootState) => state.testReducer)
  const { data, error, isLoading } = useGetWeatherByNameQuery('Mar del plata')
  console.log(data, error, isLoading)

  return (
    <>
      <Head>
        <title>Weather App | Zeleri</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ height: '92.8vh', marginLeft: '25rem' }}>
        Hola
      </div>
    </>
  )
}
